-- Create a table to store user roles
CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- Create a table to link users to roles
CREATE TABLE user_roles (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

-- Insert 'admin' and 'user' roles
INSERT INTO roles (name) VALUES ('admin'), ('user');

-- Function to check if a user has a specific role
CREATE OR REPLACE FUNCTION public.has_role(role_name TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM user_roles ur
    JOIN roles r ON ur.role_id = r.id
    WHERE ur.user_id = auth.uid() AND r.name = role_name
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RLS policies for admin access

-- Allow admins to read all tours
DROP POLICY IF EXISTS "Authenticated users can select all tours" ON public.tours;
CREATE POLICY "Admins can select all tours" ON public.tours
  FOR SELECT USING (public.has_role('admin'));

-- Allow admins to read all expense reports
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.expense_reports;
CREATE POLICY "Admins can select all expense reports" ON public.expense_reports
  FOR SELECT USING (public.has_role('admin'));

-- Allow admins to read all profiles
DROP POLICY IF EXISTS "Authenticated users can read profiles" ON public.guide_profiles;
CREATE POLICY "Admins can select all profiles" ON public.guide_profiles
  FOR SELECT USING (public.has_role('admin'));

-- Allow non-admin users to see their own data
CREATE POLICY "Users can see their own tours" ON public.tours
  FOR SELECT USING (auth.uid() = tour_guide_id);

CREATE POLICY "Users can see their own expense reports" ON public.expense_reports
  FOR SELECT USING (auth.uid() = guide_id);

CREATE POLICY "Users can see their own profile" ON public.guide_profiles
  FOR SELECT USING (id = auth.uid());
